spring:
  application:
    name: springcloud-system
  datasource:
    url: jdbc:mysql://${dataSourceUrl}:3306/springsecurity?userUnicode=true&characterencoding=utf8mb4&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8008
eureka:
  client:
    service-url:
      defaultZone: http://${eurekaHost}:8001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: ${clientIp}

dataSourceUrl: localhost

eurekaHost: localhost

clientIp: localhost
security:
  oauth2:
    client:
#      access-token-uri: /oauth/token
      client-id: system
      client-secret: system

mybatis:
  mapper-locations: classpath:/mapping/*.xml
