spring:
  application:
    name: springcloud-provider # eureka注册名字
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://${eurekaHost}:8001/eureka # eureka地址  使用localhost:8001访问
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    # 如果部署到不同服务器需要指定ip-address为部署的服务器的公网ip
    ip-address: ${clientIp}

clientIp: localhost

eurekaHost: localhost

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8008/auth/getAccessToken
    client:
      client-id: provider
      client-secret: provider
      access-token-uri: http://localhost:8008/oauth/token
      grant-type: password
      scope: provider


