spring:
  application:
    name: springcloud-provider # eureka注册名字
  datasource:
    url: jdbc:mysql://${dataSourceUrl}:3306/springsecurity?userUnicode=true&characterencoding=utf8mb4&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: localhost
    username: qiqi
    password: 123456
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 5
        prefetch: 1
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://${eurekaHost}:8001/eureka # eureka地址  使用localhost:8001访问
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 如果部署到不同服务器需要指定ip-address为部署的服务器的公网ip
    ip-address: ${clientIp}

dataSourceUrl: localhost

clientIp: localhost

eurekaHost: localhost

security:
  oauth2:
    resource:
#      user-info-uri: http://localhost:8008/auth/user
      token-info-uri: http://localhost:8008/oauth/check_token
    client:
      client-id: provider
      client-secret: provider
mybatis:
  mapper-locations: classpath*:/sqlmap/**/*.xml

