spring:
  application:
    name: springcloud-provider # eureka注册名字
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka # eureka地址  使用localhost:8001访问
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}