spring:
  application:
    name: springcloud-consumer-ribbon
server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://${eurekaHost}:8001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ip-address: ${clientIp}
#springcloud-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eurekaHost: localhost
clientIp: localhost
