spring:
  application:
    name: springcloud-eureka
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://${eurekaHost}:8001/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}


eurekaHost: localhost

